# Generated by Django 3.1.5 on 2021-12-15 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211215_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(default='current date', max_length=10000),
        ),
    ]
